//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace deneme {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class ds_Hareket : DataSet {
        
        private tbl_hareketDataTable tabletbl_hareket;
        
        public ds_Hareket() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected ds_Hareket(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["tbl_hareket"] != null)) {
                    this.Tables.Add(new tbl_hareketDataTable(ds.Tables["tbl_hareket"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public tbl_hareketDataTable tbl_hareket {
            get {
                return this.tabletbl_hareket;
            }
        }
        
        public override DataSet Clone() {
            ds_Hareket cln = ((ds_Hareket)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["tbl_hareket"] != null)) {
                this.Tables.Add(new tbl_hareketDataTable(ds.Tables["tbl_hareket"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tabletbl_hareket = ((tbl_hareketDataTable)(this.Tables["tbl_hareket"]));
            if ((this.tabletbl_hareket != null)) {
                this.tabletbl_hareket.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "ds_Hareket";
            this.Prefix = "";
            this.Namespace = "http://www.tempuri.org/ds_Hareket.xsd";
            this.Locale = new System.Globalization.CultureInfo("tr-TR");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tabletbl_hareket = new tbl_hareketDataTable();
            this.Tables.Add(this.tabletbl_hareket);
        }
        
        private bool ShouldSerializetbl_hareket() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void tbl_hareketRowChangeEventHandler(object sender, tbl_hareketRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class tbl_hareketDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnHareketID;
            
            private DataColumn columnTarih;
            
            private DataColumn columnSaat;
            
            private DataColumn columnSil;
            
            private DataColumn columnKartID;
            
            private DataColumn columnHarTur;
            
            private DataColumn columnHarYonu;
            
            private DataColumn columnIletisim;
            
            private DataColumn columnAraSonuc;
            
            private DataColumn columnKonu;
            
            private DataColumn columnGorusme;
            
            private DataColumn columnGorTarih;
            
            private DataColumn columnGorZaman;
            
            private DataColumn columnGorDurum;
            
            private DataColumn columnGorSonuc;
            
            private DataColumn columnGorNot;
            
            private DataColumn columnAdmin;
            
            private DataColumn columnHarDurum;
            
            private DataColumn columnSonYonu;
            
            private DataColumn columnUsers;
            
            private DataColumn columnUserName;
            
            internal tbl_hareketDataTable() : 
                    base("tbl_hareket") {
                this.InitClass();
            }
            
            internal tbl_hareketDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn HareketIDColumn {
                get {
                    return this.columnHareketID;
                }
            }
            
            internal DataColumn TarihColumn {
                get {
                    return this.columnTarih;
                }
            }
            
            internal DataColumn SaatColumn {
                get {
                    return this.columnSaat;
                }
            }
            
            internal DataColumn SilColumn {
                get {
                    return this.columnSil;
                }
            }
            
            internal DataColumn KartIDColumn {
                get {
                    return this.columnKartID;
                }
            }
            
            internal DataColumn HarTurColumn {
                get {
                    return this.columnHarTur;
                }
            }
            
            internal DataColumn HarYonuColumn {
                get {
                    return this.columnHarYonu;
                }
            }
            
            internal DataColumn IletisimColumn {
                get {
                    return this.columnIletisim;
                }
            }
            
            internal DataColumn AraSonucColumn {
                get {
                    return this.columnAraSonuc;
                }
            }
            
            internal DataColumn KonuColumn {
                get {
                    return this.columnKonu;
                }
            }
            
            internal DataColumn GorusmeColumn {
                get {
                    return this.columnGorusme;
                }
            }
            
            internal DataColumn GorTarihColumn {
                get {
                    return this.columnGorTarih;
                }
            }
            
            internal DataColumn GorZamanColumn {
                get {
                    return this.columnGorZaman;
                }
            }
            
            internal DataColumn GorDurumColumn {
                get {
                    return this.columnGorDurum;
                }
            }
            
            internal DataColumn GorSonucColumn {
                get {
                    return this.columnGorSonuc;
                }
            }
            
            internal DataColumn GorNotColumn {
                get {
                    return this.columnGorNot;
                }
            }
            
            internal DataColumn AdminColumn {
                get {
                    return this.columnAdmin;
                }
            }
            
            internal DataColumn HarDurumColumn {
                get {
                    return this.columnHarDurum;
                }
            }
            
            internal DataColumn SonYonuColumn {
                get {
                    return this.columnSonYonu;
                }
            }
            
            internal DataColumn UsersColumn {
                get {
                    return this.columnUsers;
                }
            }
            
            internal DataColumn UserNameColumn {
                get {
                    return this.columnUserName;
                }
            }
            
            public tbl_hareketRow this[int index] {
                get {
                    return ((tbl_hareketRow)(this.Rows[index]));
                }
            }
            
            public event tbl_hareketRowChangeEventHandler tbl_hareketRowChanged;
            
            public event tbl_hareketRowChangeEventHandler tbl_hareketRowChanging;
            
            public event tbl_hareketRowChangeEventHandler tbl_hareketRowDeleted;
            
            public event tbl_hareketRowChangeEventHandler tbl_hareketRowDeleting;
            
            public void Addtbl_hareketRow(tbl_hareketRow row) {
                this.Rows.Add(row);
            }
            
            public tbl_hareketRow Addtbl_hareketRow(
                        System.DateTime Tarih, 
                        System.DateTime Saat, 
                        System.Byte Sil, 
                        int KartID, 
                        string HarTur, 
                        int HarYonu, 
                        string Iletisim, 
                        string AraSonuc, 
                        string Konu, 
                        int Gorusme, 
                        System.DateTime GorTarih, 
                        System.DateTime GorZaman, 
                        string GorDurum, 
                        string GorSonuc, 
                        string GorNot, 
                        string Admin, 
                        string HarDurum, 
                        int SonYonu, 
                        int Users, 
                        string UserName) {
                tbl_hareketRow rowtbl_hareketRow = ((tbl_hareketRow)(this.NewRow()));
                rowtbl_hareketRow.ItemArray = new object[] {
                        null,
                        Tarih,
                        Saat,
                        Sil,
                        KartID,
                        HarTur,
                        HarYonu,
                        Iletisim,
                        AraSonuc,
                        Konu,
                        Gorusme,
                        GorTarih,
                        GorZaman,
                        GorDurum,
                        GorSonuc,
                        GorNot,
                        Admin,
                        HarDurum,
                        SonYonu,
                        Users,
                        UserName};
                this.Rows.Add(rowtbl_hareketRow);
                return rowtbl_hareketRow;
            }
            
            public tbl_hareketRow FindByHareketID(int HareketID) {
                return ((tbl_hareketRow)(this.Rows.Find(new object[] {
                            HareketID})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                tbl_hareketDataTable cln = ((tbl_hareketDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new tbl_hareketDataTable();
            }
            
            internal void InitVars() {
                this.columnHareketID = this.Columns["HareketID"];
                this.columnTarih = this.Columns["Tarih"];
                this.columnSaat = this.Columns["Saat"];
                this.columnSil = this.Columns["Sil"];
                this.columnKartID = this.Columns["KartID"];
                this.columnHarTur = this.Columns["HarTur"];
                this.columnHarYonu = this.Columns["HarYonu"];
                this.columnIletisim = this.Columns["Iletisim"];
                this.columnAraSonuc = this.Columns["AraSonuc"];
                this.columnKonu = this.Columns["Konu"];
                this.columnGorusme = this.Columns["Gorusme"];
                this.columnGorTarih = this.Columns["GorTarih"];
                this.columnGorZaman = this.Columns["GorZaman"];
                this.columnGorDurum = this.Columns["GorDurum"];
                this.columnGorSonuc = this.Columns["GorSonuc"];
                this.columnGorNot = this.Columns["GorNot"];
                this.columnAdmin = this.Columns["Admin"];
                this.columnHarDurum = this.Columns["HarDurum"];
                this.columnSonYonu = this.Columns["SonYonu"];
                this.columnUsers = this.Columns["Users"];
                this.columnUserName = this.Columns["UserName"];
            }
            
            private void InitClass() {
                this.columnHareketID = new DataColumn("HareketID", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnHareketID);
                this.columnTarih = new DataColumn("Tarih", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnTarih);
                this.columnSaat = new DataColumn("Saat", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnSaat);
                this.columnSil = new DataColumn("Sil", typeof(System.Byte), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnSil);
                this.columnKartID = new DataColumn("KartID", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnKartID);
                this.columnHarTur = new DataColumn("HarTur", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnHarTur);
                this.columnHarYonu = new DataColumn("HarYonu", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnHarYonu);
                this.columnIletisim = new DataColumn("Iletisim", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnIletisim);
                this.columnAraSonuc = new DataColumn("AraSonuc", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnAraSonuc);
                this.columnKonu = new DataColumn("Konu", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnKonu);
                this.columnGorusme = new DataColumn("Gorusme", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnGorusme);
                this.columnGorTarih = new DataColumn("GorTarih", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnGorTarih);
                this.columnGorZaman = new DataColumn("GorZaman", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnGorZaman);
                this.columnGorDurum = new DataColumn("GorDurum", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnGorDurum);
                this.columnGorSonuc = new DataColumn("GorSonuc", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnGorSonuc);
                this.columnGorNot = new DataColumn("GorNot", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnGorNot);
                this.columnAdmin = new DataColumn("Admin", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnAdmin);
                this.columnHarDurum = new DataColumn("HarDurum", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnHarDurum);
                this.columnSonYonu = new DataColumn("SonYonu", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnSonYonu);
                this.columnUsers = new DataColumn("Users", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnUsers);
                this.columnUserName = new DataColumn("UserName", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnUserName);
                this.Constraints.Add(new UniqueConstraint("Constraint1", new DataColumn[] {
                                this.columnHareketID}, true));
                this.columnHareketID.AutoIncrement = true;
                this.columnHareketID.AllowDBNull = false;
                this.columnHareketID.ReadOnly = true;
                this.columnHareketID.Unique = true;
                this.columnSil.AllowDBNull = false;
                this.columnKartID.AllowDBNull = false;
                this.columnHarTur.AllowDBNull = false;
                this.columnHarYonu.AllowDBNull = false;
                this.columnIletisim.AllowDBNull = false;
                this.columnAraSonuc.AllowDBNull = false;
                this.columnKonu.AllowDBNull = false;
                this.columnGorusme.AllowDBNull = false;
                this.columnGorDurum.AllowDBNull = false;
                this.columnGorSonuc.AllowDBNull = false;
                this.columnGorNot.AllowDBNull = false;
                this.columnAdmin.AllowDBNull = false;
                this.columnHarDurum.AllowDBNull = false;
                this.columnSonYonu.AllowDBNull = false;
                this.columnUsers.AllowDBNull = false;
                this.columnUserName.AllowDBNull = false;
            }
            
            public tbl_hareketRow Newtbl_hareketRow() {
                return ((tbl_hareketRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new tbl_hareketRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(tbl_hareketRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.tbl_hareketRowChanged != null)) {
                    this.tbl_hareketRowChanged(this, new tbl_hareketRowChangeEvent(((tbl_hareketRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.tbl_hareketRowChanging != null)) {
                    this.tbl_hareketRowChanging(this, new tbl_hareketRowChangeEvent(((tbl_hareketRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.tbl_hareketRowDeleted != null)) {
                    this.tbl_hareketRowDeleted(this, new tbl_hareketRowChangeEvent(((tbl_hareketRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.tbl_hareketRowDeleting != null)) {
                    this.tbl_hareketRowDeleting(this, new tbl_hareketRowChangeEvent(((tbl_hareketRow)(e.Row)), e.Action));
                }
            }
            
            public void Removetbl_hareketRow(tbl_hareketRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class tbl_hareketRow : DataRow {
            
            private tbl_hareketDataTable tabletbl_hareket;
            
            internal tbl_hareketRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tabletbl_hareket = ((tbl_hareketDataTable)(this.Table));
            }
            
            public int HareketID {
                get {
                    return ((int)(this[this.tabletbl_hareket.HareketIDColumn]));
                }
                set {
                    this[this.tabletbl_hareket.HareketIDColumn] = value;
                }
            }
            
            public System.DateTime Tarih {
                get {
                    try {
                        return ((System.DateTime)(this[this.tabletbl_hareket.TarihColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletbl_hareket.TarihColumn] = value;
                }
            }
            
            public System.DateTime Saat {
                get {
                    try {
                        return ((System.DateTime)(this[this.tabletbl_hareket.SaatColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletbl_hareket.SaatColumn] = value;
                }
            }
            
            public System.Byte Sil {
                get {
                    return ((System.Byte)(this[this.tabletbl_hareket.SilColumn]));
                }
                set {
                    this[this.tabletbl_hareket.SilColumn] = value;
                }
            }
            
            public int KartID {
                get {
                    return ((int)(this[this.tabletbl_hareket.KartIDColumn]));
                }
                set {
                    this[this.tabletbl_hareket.KartIDColumn] = value;
                }
            }
            
            public string HarTur {
                get {
                    return ((string)(this[this.tabletbl_hareket.HarTurColumn]));
                }
                set {
                    this[this.tabletbl_hareket.HarTurColumn] = value;
                }
            }
            
            public int HarYonu {
                get {
                    return ((int)(this[this.tabletbl_hareket.HarYonuColumn]));
                }
                set {
                    this[this.tabletbl_hareket.HarYonuColumn] = value;
                }
            }
            
            public string Iletisim {
                get {
                    return ((string)(this[this.tabletbl_hareket.IletisimColumn]));
                }
                set {
                    this[this.tabletbl_hareket.IletisimColumn] = value;
                }
            }
            
            public string AraSonuc {
                get {
                    return ((string)(this[this.tabletbl_hareket.AraSonucColumn]));
                }
                set {
                    this[this.tabletbl_hareket.AraSonucColumn] = value;
                }
            }
            
            public string Konu {
                get {
                    return ((string)(this[this.tabletbl_hareket.KonuColumn]));
                }
                set {
                    this[this.tabletbl_hareket.KonuColumn] = value;
                }
            }
            
            public int Gorusme {
                get {
                    return ((int)(this[this.tabletbl_hareket.GorusmeColumn]));
                }
                set {
                    this[this.tabletbl_hareket.GorusmeColumn] = value;
                }
            }
            
            public System.DateTime GorTarih {
                get {
                    try {
                        return ((System.DateTime)(this[this.tabletbl_hareket.GorTarihColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletbl_hareket.GorTarihColumn] = value;
                }
            }
            
            public System.DateTime GorZaman {
                get {
                    try {
                        return ((System.DateTime)(this[this.tabletbl_hareket.GorZamanColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tabletbl_hareket.GorZamanColumn] = value;
                }
            }
            
            public string GorDurum {
                get {
                    return ((string)(this[this.tabletbl_hareket.GorDurumColumn]));
                }
                set {
                    this[this.tabletbl_hareket.GorDurumColumn] = value;
                }
            }
            
            public string GorSonuc {
                get {
                    return ((string)(this[this.tabletbl_hareket.GorSonucColumn]));
                }
                set {
                    this[this.tabletbl_hareket.GorSonucColumn] = value;
                }
            }
            
            public string GorNot {
                get {
                    return ((string)(this[this.tabletbl_hareket.GorNotColumn]));
                }
                set {
                    this[this.tabletbl_hareket.GorNotColumn] = value;
                }
            }
            
            public string Admin {
                get {
                    return ((string)(this[this.tabletbl_hareket.AdminColumn]));
                }
                set {
                    this[this.tabletbl_hareket.AdminColumn] = value;
                }
            }
            
            public string HarDurum {
                get {
                    return ((string)(this[this.tabletbl_hareket.HarDurumColumn]));
                }
                set {
                    this[this.tabletbl_hareket.HarDurumColumn] = value;
                }
            }
            
            public int SonYonu {
                get {
                    return ((int)(this[this.tabletbl_hareket.SonYonuColumn]));
                }
                set {
                    this[this.tabletbl_hareket.SonYonuColumn] = value;
                }
            }
            
            public int Users {
                get {
                    return ((int)(this[this.tabletbl_hareket.UsersColumn]));
                }
                set {
                    this[this.tabletbl_hareket.UsersColumn] = value;
                }
            }
            
            public string UserName {
                get {
                    return ((string)(this[this.tabletbl_hareket.UserNameColumn]));
                }
                set {
                    this[this.tabletbl_hareket.UserNameColumn] = value;
                }
            }
            
            public bool IsTarihNull() {
                return this.IsNull(this.tabletbl_hareket.TarihColumn);
            }
            
            public void SetTarihNull() {
                this[this.tabletbl_hareket.TarihColumn] = System.Convert.DBNull;
            }
            
            public bool IsSaatNull() {
                return this.IsNull(this.tabletbl_hareket.SaatColumn);
            }
            
            public void SetSaatNull() {
                this[this.tabletbl_hareket.SaatColumn] = System.Convert.DBNull;
            }
            
            public bool IsGorTarihNull() {
                return this.IsNull(this.tabletbl_hareket.GorTarihColumn);
            }
            
            public void SetGorTarihNull() {
                this[this.tabletbl_hareket.GorTarihColumn] = System.Convert.DBNull;
            }
            
            public bool IsGorZamanNull() {
                return this.IsNull(this.tabletbl_hareket.GorZamanColumn);
            }
            
            public void SetGorZamanNull() {
                this[this.tabletbl_hareket.GorZamanColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class tbl_hareketRowChangeEvent : EventArgs {
            
            private tbl_hareketRow eventRow;
            
            private DataRowAction eventAction;
            
            public tbl_hareketRowChangeEvent(tbl_hareketRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public tbl_hareketRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
